#!/bin/sh
post_install(){
    echo "==> Linking init and power functions to busybox"
    for i in init halt poweroff reboot; do
        ln -sf $(which busybox) /sbin/$i
    done
    echo ":: Append 'init=/sbin/init' to your kernel line in your bootloader"
    echo "   to replace your current init with minirc"
}

post_remove(){
    echo "==> Clean up links"
    rm -f /sbin/{init,halt,poweroff,reboot}
}
